### ISSUE TITLE
能否加一个弹出的sc持续时长自己设置的功能呢

### ISSUE THREAD

**Issue by whj-jack** [eeelester/bilibili-fullscreen-sc#1]
现在一些大金额的sc会一直放在那里，感觉如果能自己设置持续时长就好了，希望大佬有空加个这个功能

**Comment by eeelester** [comment]
> 现在一些大金额的sc会一直放在那里，感觉如果能自己设置持续时长就好了，希望大佬有空加个这个功能
我感觉这个需求改为：每一个sc卡片右上角都有个X，供用户自行删除，这样子会不会更好呢？

**Comment by whj-jack** [comment]
> > 现在一些大金额的sc会一直放在那里，感觉如果能自己设置持续时长就好了，希望大佬有空加个这个功能
> 
> 我感觉这个需求改为：每一个sc卡片右上角都有个X，供用户自行删除，这样子会不会更好呢？

这样也能满足这个需求，但是会多一步需要手动删除，会麻烦一点。我感觉sc基本存在30s~60s就已经足够我看完并且了解了，所以剩下的时间挂在那里基本没啥意义

**Comment by eeelester** [comment]
> > > 现在一些大金额的sc会一直放在那里，感觉如果能自己设置持续时长就好了，希望大佬有空加个这个功能
> > 
> > 
> > 我感觉这个需求改为：每一个sc卡片右上角都有个X，供用户自行删除，这样子会不会更好呢？
> 
> 这样也能满足这个需求，但是会多一步需要手动删除，会麻烦一点。我感觉sc基本存在30s~60s就已经足够我看完并且了解了，所以剩下的时间挂在那里基本没啥意义

已增加：(https://github.com/eeelester/bilibili-fullscreen-sc/commit/275035879cdae99fd18202d559e43f82934d937e)
