### ISSUE TITLE
从昨天更新后好像就不能全票显示SC了

### ISSUE THREAD

**Issue by Ther-LF** [eeelester/bilibili-fullscreen-sc#2]
昨天更新后，就不能全屏显示SC了，并且那个SC的插件一直是暗着的。

**Comment by eeelester** [comment]
你的插件版本是多少？全屏是包括全屏和网页全屏都不能显示SC吗？

**Comment by Ther-LF** [comment]
0.8.2，网页全屏也不行，chrom版本是131.0.6778.205。我卸载了重新安装了一遍还是不行。

**Comment by eeelester** [comment]
我的插件版本和浏览器版本和你一致，但是没能复现这个问题，我这里使用一切正常....所以确认下：
1. 进入直播间，网页右侧有已存在的SC时，打开全屏/网页全屏后有显示SC列表吗？
2. 全屏了以后后续的SC都没有显示在列表中？

**Comment by eeelester** [comment]
还有SC的图标暗的情况，这个是显示异常。我已经取消开关的功能了，所以是常开的，这个后续我会看看怎么修复

**Comment by Ther-LF** [comment]
没有哇，全都没有QAQ，网页全屏和全屏都不行，后续的SC也没有在列表中

**Comment by eeelester** [comment]
主要我这边不好复现，你可以发下你的qq吗？我加你后续帮你看下

**Comment by Ther-LF** [comment]
我敲太麻烦你了QAQ，谢谢谢谢。
2639852836

**Comment by eeelester** [comment]
已经修复并发布，v0.8.3
